import Foundation

/// A deliberately tiny harness. No XCTest: the app builds with swiftc and a
/// bundle script, not an .xcodeproj, so a test target would be the only reason
/// to introduce one.
enum T {
    nonisolated(unsafe) static var passed = 0
    nonisolated(unsafe) static var failed = 0
    nonisolated(unsafe) static var current = ""

    static func suite(_ name: String) {
        current = name
        print("\n\(name)")
    }

    static func ok(_ id: String, _ cond: Bool, _ detail: @autoclosure () -> String = "") {
        if cond { passed += 1; print("  ok   \(id)") }
        else {
            failed += 1
            let d = detail()
            print("  FAIL \(id)\(d.isEmpty ? "" : "  — \(d)")")
        }
    }

    /// Announce what was NOT run. A suite that silently does nothing reads
    /// exactly like a suite that passed.
    static func skip(_ id: String, _ why: String) {
        print("  skip \(id)  \(why)")
    }

    static func eq<V: Equatable>(_ id: String, _ got: V, _ want: V) {
        ok(id, got == want, "got \(got), want \(want)")
    }

    static func summary() -> Int32 {
        print("\n\(passed) passed, \(failed) failed")
        return failed == 0 ? 0 : 1
    }

    // MARK: - the corpus

    /// CrookTests/Fixtures, resolved from THIS SOURCE FILE.
    ///
    /// `#filePath` is baked in at compile time from the checkout being built,
    /// so a fresh clone anywhere on any machine finds its own fixture. Never an
    /// absolute path, never anyone's home directory.
    ///
    /// Standardized, and that is load-bearing: ReachClassifier compares
    /// `url.standardizedFileURL.path` against its idea of the home directory,
    /// and standardizing strips a leading `/private` when the file exists. A
    /// checkout under /tmp or /var — which is where CI puts one — would
    /// otherwise hand the classifier two spellings of the same directory and
    /// every personal-scope role would read as a project one.
    static let fixtureRoot: URL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .appendingPathComponent("Fixtures", isDirectory: true)
        .standardizedFileURL

    /// The directory inside the fixture that stands in for the user's home.
    /// `corpus/home/.claude/...` is what makes the personal-scope roles and the
    /// `~/` path anchor testable without reading the machine running the suite.
    static let fixtureHome: URL = fixtureRoot
        .appendingPathComponent("corpus/home", isDirectory: true)

    /// True when the suite is running against the checked-in synthetic corpus,
    /// which is the default and the only configuration the counts describe.
    static let usingSyntheticCorpus: Bool =
        ProcessInfo.processInfo.environment["CROOK_CORPUS"] == nil

    /// The frozen corpus. Every corpus assertion runs against this exact list,
    /// never against a live walk of the disk.
    ///
    /// By default it is `CrookTests/Fixtures/corpus.txt`: 43 checked-in files of
    /// entirely invented content, generated by `Fixtures/generate.swift` and
    /// committed, so the suite needs no setup step. Entries there are relative
    /// to the Fixtures directory.
    ///
    /// TO RUN AGAINST A REAL CORPUS instead — a machine's actual ~/.claude tree,
    /// say — point CROOK_CORPUS at a file holding one path per line:
    ///
    ///     find ~/.claude -name '*.md' > /tmp/mine.txt
    ///     CROOK_CORPUS=/tmp/mine.txt ./scripts/test.sh bytes deadpath
    ///
    /// Absolute entries are used as-is; relative ones resolve against the
    /// directory holding that file. The counts below describe the synthetic
    /// corpus and will not hold for any other one, so expect those to fail. The
    /// structural assertions do hold for every corpus: byte-identical round
    /// trips, no live path reported dead, every finding's offsets slicing back
    /// to the path it names, and the role gate hiding nothing.
    static let fixture: [String] = {
        let env = ProcessInfo.processInfo.environment["CROOK_CORPUS"]
        let listURL = env.map { URL(fileURLWithPath: ($0 as NSString).expandingTildeInPath) }
            ?? fixtureRoot.appendingPathComponent("corpus.txt")
        let base = listURL.deletingLastPathComponent()
        return ((try? String(contentsOf: listURL, encoding: .utf8)) ?? "")
            .split(separator: "\n")
            .map(String.init)
            .filter { !$0.isEmpty && !$0.hasPrefix("#") }
            .map { $0.hasPrefix("/") ? $0 : base.appendingPathComponent($0).path }
    }()

    /// Runs `body` with the fixture's `home/` directory standing in for the
    /// user's home, so `~/.claude/...` resolves inside the corpus. Use this for
    /// every assertion about a specific FIXTURE FILE: those files live under
    /// `corpus/home`, and only this makes them personal-scope.
    ///
    /// Scoped rather than global on purpose. ValidationTests asserts about path
    /// classification alone and is correct against whatever home it finds, and
    /// a global override would silently move the ground under it.
    @discardableResult
    static func withFixtureHome<R>(_ body: () -> R) -> R {
        let saved = Paths.homeOverride
        Paths.homeOverride = fixtureHome.path
        defer { Paths.homeOverride = saved }
        return body()
    }

    /// Runs `body` with the home the CORPUS belongs to: the fixture's when the
    /// corpus is the synthetic one, the machine's own when CROOK_CORPUS names a
    /// real tree. Use this for the census loops — a real corpus's `~/.claude`
    /// files are personal to THAT machine, and classifying them against the
    /// fixture's home would call every one of them a project file.
    @discardableResult
    static func withCorpusHome<R>(_ body: () -> R) -> R {
        guard usingSyntheticCorpus else { return body() }
        return withFixtureHome(body)
    }

    /// A path inside the fixture corpus, from its path relative to `corpus/`.
    static func f(_ rel: String) -> String {
        fixtureRoot.appendingPathComponent("corpus/" + rel).path
    }

    static func read(_ path: String) -> String {
        (try? String(contentsOfFile: path, encoding: .utf8)) ?? ""
    }
}

/// A provider that behaves exactly like the local one but answers to a
/// different name. Enough to prove that per-machine state stays separated
/// without needing a second machine.
final class StubProvider: FileProvider {
    let id: String
    init(id: String) { self.id = id }
    var displayName: String { id }
    var homePath: String { Paths.home }
    var isLocal: Bool { false }
    var isConnected: Bool { true }
    private let inner = LocalProvider()
    func list(_ p: String) -> [FSEntry] { inner.list(p) }
    func exists(_ p: String) -> Bool { inner.exists(p) }
    func isDirectory(_ p: String) -> Bool { inner.isDirectory(p) }
    func fingerprint(_ p: String) -> (mtime: Double, size: Int)? { inner.fingerprint(p) }
    func contents(_ p: String) -> Data? { inner.contents(p) }
    func write(_ d: Data, to p: String) throws { try inner.write(d, to: p) }
    func symlinkDestination(_ p: String) -> String? { inner.symlinkDestination(p) }
}
